package S01.model.admin.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 31 12:31:13 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminFormDetailEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FormId,
        ModuleId,
        FormName,
        FormDescription,
        FormType,
        EnteredBy,
        EnteredOn,
        LastEditedBy,
        LastEditedOn,
        Active,
        AdminRightsDetailEO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FORMID = AttributesEnum.FormId.index();
    public static final int MODULEID = AttributesEnum.ModuleId.index();
    public static final int FORMNAME = AttributesEnum.FormName.index();
    public static final int FORMDESCRIPTION = AttributesEnum.FormDescription.index();
    public static final int FORMTYPE = AttributesEnum.FormType.index();
    public static final int ENTEREDBY = AttributesEnum.EnteredBy.index();
    public static final int ENTEREDON = AttributesEnum.EnteredOn.index();
    public static final int LASTEDITEDBY = AttributesEnum.LastEditedBy.index();
    public static final int LASTEDITEDON = AttributesEnum.LastEditedOn.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int ADMINRIGHTSDETAILEO = AttributesEnum.AdminRightsDetailEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AdminFormDetailEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("S01.model.admin.eo.AdminFormDetailEO");
    }


    /**
     * Gets the attribute value for FormId, using the alias name FormId.
     * @return the value of FormId
     */
    public Number getFormId() {
        return (Number) getAttributeInternal(FORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FormId.
     * @param value value to set the FormId
     */
    public void setFormId(Number value) {
        setAttributeInternal(FORMID, value);
    }

    /**
     * Gets the attribute value for FormName, using the alias name FormName.
     * @return the value of FormName
     */
    public String getFormName() {
        return (String) getAttributeInternal(FORMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FormName.
     * @param value value to set the FormName
     */
    public void setFormName(String value) {
        setAttributeInternal(FORMNAME, value);
    }

    /**
     * Gets the attribute value for FormDescription, using the alias name FormDescription.
     * @return the value of FormDescription
     */
    public String getFormDescription() {
        return (String) getAttributeInternal(FORMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FormDescription.
     * @param value value to set the FormDescription
     */
    public void setFormDescription(String value) {
        setAttributeInternal(FORMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for FormType, using the alias name FormType.
     * @return the value of FormType
     */
    public String getFormType() {
        return (String) getAttributeInternal(FORMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FormType.
     * @param value value to set the FormType
     */
    public void setFormType(String value) {
        setAttributeInternal(FORMTYPE, value);
    }

    /**
     * Gets the attribute value for EnteredBy, using the alias name EnteredBy.
     * @return the value of EnteredBy
     */
    public Number getEnteredBy() {
        return (Number) getAttributeInternal(ENTEREDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredBy.
     * @param value value to set the EnteredBy
     */
    public void setEnteredBy(Number value) {
        setAttributeInternal(ENTEREDBY, value);
    }

    /**
     * Gets the attribute value for EnteredOn, using the alias name EnteredOn.
     * @return the value of EnteredOn
     */
    public Date getEnteredOn() {
        return (Date) getAttributeInternal(ENTEREDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredOn.
     * @param value value to set the EnteredOn
     */
    public void setEnteredOn(Date value) {
        setAttributeInternal(ENTEREDON, value);
    }

    /**
     * Gets the attribute value for LastEditedBy, using the alias name LastEditedBy.
     * @return the value of LastEditedBy
     */
    public Number getLastEditedBy() {
        return (Number) getAttributeInternal(LASTEDITEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedBy.
     * @param value value to set the LastEditedBy
     */
    public void setLastEditedBy(Number value) {
        setAttributeInternal(LASTEDITEDBY, value);
    }

    /**
     * Gets the attribute value for LastEditedOn, using the alias name LastEditedOn.
     * @return the value of LastEditedOn
     */
    public Date getLastEditedOn() {
        return (Date) getAttributeInternal(LASTEDITEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedOn.
     * @param value value to set the LastEditedOn
     */
    public void setLastEditedOn(Date value) {
        setAttributeInternal(LASTEDITEDON, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the value of Active
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for ModuleId, using the alias name ModuleId.
     * @return the value of ModuleId
     */
    public Number getModuleId() {
        return (Number) getAttributeInternal(MODULEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModuleId.
     * @param value value to set the ModuleId
     */
    public void setModuleId(Number value) {
        setAttributeInternal(MODULEID, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAdminRightsDetailEO() {
        return (RowIterator) getAttributeInternal(ADMINRIGHTSDETAILEO);
    }


    /**
     * @param formId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number formId) {
        return new Key(new Object[] { formId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("ADMIN_FORM_DETAIL_S", getDBTransaction());
        setFormId(seq.getSequenceNumber());
        
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

