package S01.model.admin.vo;

import S01.model.admin.vo.common.AdminUsersVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 19 11:36:21 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminUsersVOImpl extends ViewObjectImpl implements AdminUsersVO {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminUsersVOImpl() {
    }
    public String doLogin(String pUser_name,String pUser_password){
        
        setWhereClause("USER_NAME='"+pUser_name+"' and USER_PASSWORD='"+pUser_password+"'");
        executeQuery();
        if (getRowCount()>0){
            return "Y";
        }
            return "N";
        
        
        }
    
}

