package S01.model.admin.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 19 13:55:22 PKT 2023
// ---------------------------------------------------------------------
public interface AdminUsersVO extends ViewObject {
    String doLogin(String pUser_name, String pUser_password);
}

